from os import PathLike
from typing import Any, Iterator, List, Literal, Optional, Tuple, Union, overload

import numpy as np
from numpy.typing import NDArray

_PathInput = Union[str, PathLike[str]]
_FloatVector = NDArray[np.float64]
_IntVector = NDArray[np.int64]
_FieldValue = Union[bool, int, float, str, List[str], _IntVector, _FloatVector]
_GFileValue = Union[_FieldValue, "KFile"]


class Error(Exception): ...
class IOError(Error): ...
class ValidationError(Error): ...
class FieldError(Error): ...


class ParseError(Error):
    filename: str
    line: int
    column: int


class CocosResult:
    candidates: List[int]
    diagnostic: str
    selected: Optional[int]

    def is_unique(self) -> bool: ...
    def is_ambiguous(self) -> bool: ...
    def has_match(self) -> bool: ...


class CocosError(Error):
    result: CocosResult


class KSection:
    def keys(self) -> List[str]: ...
    def items(self) -> List[Tuple[str, _FieldValue]]: ...
    def values(self) -> List[_FieldValue]: ...
    def get(self, name: str, default: Any = None) -> Any: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    @overload
    def __getitem__(self, name: Literal["LIMITR", "KFFCUR"], /) -> int: ...
    @overload
    def __getitem__(self, name: str, /) -> _FieldValue: ...
    def __setitem__(self, name: str, value: _FieldValue, /) -> None: ...
    def update(self, other: Any = (), /, **kwargs: Any) -> None: ...
    def setdefault(self, name: str, default: Any = None, /) -> Any: ...
    def __ior__(self, other: Any, /) -> "KSection": ...
    def __delitem__(self, name: str, /) -> None: ...
    def clear(self) -> None: ...
    @overload
    def pop(self, name: str) -> _FieldValue: ...
    @overload
    def pop(self, name: str, default: Any) -> Any: ...
    def popitem(self) -> Tuple[str, _FieldValue]: ...


class _FieldFile:
    filename: str

    def keys(self) -> List[str]: ...
    def items(self) -> List[Tuple[str, _FieldValue]]: ...
    def values(self) -> List[_FieldValue]: ...
    def get(self, name: str, default: Any = None) -> Any: ...
    def write(self, path: Optional[_PathInput] = None) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getitem__(self, name: str, /) -> Any: ...
    def __setitem__(self, name: str, value: _FieldValue, /) -> None: ...
    def update(self, other: Any = (), /, **kwargs: Any) -> None: ...
    def setdefault(self, name: str, default: Any = None, /) -> Any: ...
    def __ior__(self, other: Any, /) -> "_FieldFile": ...
    def __delitem__(self, name: str, /) -> None: ...
    def clear(self) -> None: ...
    @overload
    def pop(self, name: str) -> _FieldValue: ...
    @overload
    def pop(self, name: str, default: Any) -> Any: ...
    def popitem(self) -> Tuple[str, _FieldValue]: ...


class GFile(_FieldFile):
    def __init__(self, filename: _PathInput) -> None: ...
    cocos: CocosResult
    @overload
    def __getitem__(self, name: Literal["CASE"], /) -> str: ...
    @overload
    def __getitem__(self, name: Literal["NW", "NH", "NBBBS", "LIMITR"], /) -> int: ...
    @overload
    def __getitem__(self, name: Literal["PSIRZ"], /) -> NDArray[np.float64]: ...
    @overload
    def __getitem__(self, name: Literal["AuxNamelist"], /) -> "KFile": ...
    @overload
    def __getitem__(self, name: Literal["CURRENT"], /) -> float: ...
    @overload
    def __getitem__(self, name: str, /) -> _GFileValue: ...
    def select_cocos(self, source: int) -> None: ...
    def to_cocos(
        self,
        to_cocos: int,
        from_cocos: Optional[int] = None,
        inplace: bool = True,
    ) -> "GFile": ...


class AFile(_FieldFile):
    def __init__(self, filename: _PathInput) -> None: ...
    @overload
    def __getitem__(self, name: Literal["LIMLOC", "QMFLAG"], /) -> str: ...
    @overload
    def __getitem__(self, name: Literal["SHOT", "MCO2V", "MCO2R"], /) -> int: ...
    @overload
    def __getitem__(self, name: Literal["CHISQ"], /) -> float: ...
    @overload
    def __getitem__(self, name: Literal["RCO2V"], /) -> NDArray[np.float64]: ...
    @overload
    def __getitem__(self, name: str, /) -> _FieldValue: ...


class KFile:
    filename: str

    def __init__(self, filename: _PathInput) -> None: ...
    def keys(self) -> List[str]: ...
    def items(self) -> List[Tuple[str, KSection]]: ...
    def values(self) -> List[KSection]: ...
    def get(self, name: str, default: Any = None) -> Any: ...
    def write(self, path: Optional[_PathInput] = None) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getitem__(self, name: str, /) -> KSection: ...
    def __setitem__(self, name: str, value: Any, /) -> None: ...
    def update(self, other: Any = (), /, **kwargs: Any) -> None: ...
    def setdefault(self, name: str, default: Any = None, /) -> Any: ...
    def __ior__(self, other: Any, /) -> "KFile": ...
    def __delitem__(self, name: str, /) -> None: ...
    def clear(self) -> None: ...
    @overload
    def pop(self, name: str) -> KSection: ...
    @overload
    def pop(self, name: str, default: Any) -> Any: ...
    def popitem(self) -> Tuple[str, KSection]: ...


class SFile(_FieldFile):
    def __init__(self, filename: _PathInput) -> None: ...
    @overload
    def __getitem__(self, name: Literal["XLABEL", "YLABEL", "TITLE"], /) -> str: ...
    @overload
    def __getitem__(self, name: Literal["X", "Y", "DX", "DY"], /) -> NDArray[np.float64]: ...
    @overload
    def __getitem__(self, name: str, /) -> _FieldValue: ...


__version__: str

__all__ = [
    "AFile",
    "CocosError",
    "CocosResult",
    "Error",
    "FieldError",
    "GFile",
    "IOError",
    "KFile",
    "KSection",
    "ParseError",
    "SFile",
    "ValidationError",
    "__version__",
]
